In [41]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import string as string
csv_path = "Downloads/Housepy_raw.csv"
housepyraw_df = pd.read_csv(csv_path)
housepyraw_df.head()

,MLS Number,Property Type,Status,Street Number,Street Name,Unit Number,City/Location,Zip Code,County,List Price,...,List Office Name,List Agent MLSID,List Agent Full Name,Selling Office MLSID,Selling Office Name,Selling Agent MLSID,Selling Agent Full Name,Realist Owner Name,Last Change Timestamp,List Date
0,85605507,Single-Family,Sold,823,Loper,NaN,Houston,77017,Harris,"$44,500",...,The Listing Firm,oronding,Osaan Ronding,DAFA01,Reward Realty,GREENMIC,Michael Green,NaN,NaN,12/9/2014 0:00
1,67891056,Single-Family,Sold,9009,Freeland,NaN,Houston,77075,Harris,"$65,000",...,Mission Real Estate Group,jiley,Joe Iley,ILEY01,Mission Real Estate Group,jiley,Joe Iley,Trusted Legacy Hse Buyers Inc,NaN,7/15/2015 0:00
2,97810747,Single-Family,Sold,17503,Waverly Grove,NaN,Houston,77084,Harris,"$90,000",...,Intero Real Estate Services,baumd,D'Evereaux Baum,GGPR24,BHGRE Gary Greene,JilSmith,Jill Smith,NaN,NaN,3/16/2015 0:00
3,94468427,Single-Family,Sold,6619,Briar Glade,NaN,Houston,77072,Harris,"$85,900",...,Van Slyke Real Estate,vansh,Helen Van Slyke,RELM01,Realm Real Estate Professional,shaleem,Shah Haleem,Hsbc Bank Usa Na 2006-Nc3,NaN,6/1/2015 0:00
4,19671424,Single-Family,Sold,546,Glenvale,NaN,Houston,77060,Harris,"$105,000",...,"RE/MAX Northwest, REALTORS",joeluis,Jose Soria,KWPR01,Keller Williams Professionals,smgeer,Shannon Geer,NaN,NaN,3/23/2015 0:00

In [42]:
#dropping columns that wont be used to tell us anything
housepy_df = housepyraw_df[["MLS Number", "Street Number", "Street Name", "City/Location", "Zip Code", "List Price",
                           "Close Price", "Close Date", "Area", "Subdivision", "Market Area", "School District",
                           "School Elementary", "School Middle", "School High", "Sq Ft Total", "Price Sq Ft Sold", "Lot Size",
                          "Year Built", "Bedrooms", "Baths Total", "New Construction", "Pool Private", "No Of Garage Cap",
                          "Style", "CDOM"]]
housepy_df.head()

,MLS Number,Street Number,Street Name,City/Location,Zip Code,List Price,Close Price,Close Date,Area,Subdivision,...,Price Sq Ft Sold,Lot Size,Year Built,Bedrooms,Baths Total,New Construction,Pool Private,No Of Garage Cap,Style,CDOM
0,85605507,823,Loper,Houston,77017,"$44,500","$44,500",8/3/2015 0:00,3.0,Oak Meadows Sec 01,...,$35.83,6600.0,1950.0,3,1.0,False,False,2,Traditional,81
1,67891056,9009,Freeland,Houston,77075,"$65,000","$60,000",8/3/2015 0:00,3.0,Easthaven,...,$45.87,7500.0,1977.0,3,2.0,False,False,0,Traditional,19
2,97810747,17503,Waverly Grove,Houston,77084,"$90,000","$78,500",8/3/2015 0:00,8.0,Ashley Grove,...,$94.69,3900.0,1984.0,2,1.0,False,False,1,Traditional,70
3,94468427,6619,Briar Glade,Houston,77072,"$85,900","$85,000",8/3/2015 0:00,28.0,Brays Village East Sec 02,...,$46.60,4050.0,1980.0,3,2.0,False,False,2,Traditional,40
4,19671424,546,Glenvale,Houston,77060,"$105,000","$94,000",8/3/2015 0:00,12.0,Colonial Hills,...,$86.32,6090.0,1968.0,3,1.1,False,False,1,Traditional,98

In [43]:
#Output cleaned data to csv
#housepy_df.to_csv("housepy_cleaned.csv", index=False, header=True)

In [44]:
#Clean the string data type columns

housepy_df.dtypes

MLS Number             int64
Street Number         object
Street Name           object
City/Location         object
Zip Code               int64
List Price            object
Close Price           object
Close Date            object
Area                 float64
Subdivision           object
Market Area           object
School District       object
School Elementary     object
School Middle         object
School High           object
Sq Ft Total          float64
Price Sq Ft Sold      object
Lot Size             float64
Year Built           float64
Bedrooms               int64
Baths Total          float64
New Construction        bool
Pool Private            bool
No Of Garage Cap       int64
Style                 object
CDOM                   int64
dtype: object

In [45]:
housepy_df['Close Price'] = housepy_df['Close Price'].apply(lambda x: x.replace("$", ""))
housepy_df.head()

C:\Users\easha\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

,MLS Number,Street Number,Street Name,City/Location,Zip Code,List Price,Close Price,Close Date,Area,Subdivision,...,Price Sq Ft Sold,Lot Size,Year Built,Bedrooms,Baths Total,New Construction,Pool Private,No Of Garage Cap,Style,CDOM
0,85605507,823,Loper,Houston,77017,"$44,500","44,500",8/3/2015 0:00,3.0,Oak Meadows Sec 01,...,$35.83,6600.0,1950.0,3,1.0,False,False,2,Traditional,81
1,67891056,9009,Freeland,Houston,77075,"$65,000","60,000",8/3/2015 0:00,3.0,Easthaven,...,$45.87,7500.0,1977.0,3,2.0,False,False,0,Traditional,19
2,97810747,17503,Waverly Grove,Houston,77084,"$90,000","78,500",8/3/2015 0:00,8.0,Ashley Grove,...,$94.69,3900.0,1984.0,2,1.0,False,False,1,Traditional,70
3,94468427,6619,Briar Glade,Houston,77072,"$85,900","85,000",8/3/2015 0:00,28.0,Brays Village East Sec 02,...,$46.60,4050.0,1980.0,3,2.0,False,False,2,Traditional,40
4,19671424,546,Glenvale,Houston,77060,"$105,000","94,000",8/3/2015 0:00,12.0,Colonial Hills,...,$86.32,6090.0,1968.0,3,1.1,False,False,1,Traditional,98

In [46]:
housepy_df['Close Price'] = housepy_df['Close Price'].apply(lambda x: x.replace(",", ""))
housepy_df.head()
housepy_df.dtypes

C:\Users\easha\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

MLS Number             int64
Street Number         object
Street Name           object
City/Location         object
Zip Code               int64
List Price            object
Close Price           object
Close Date            object
Area                 float64
Subdivision           object
Market Area           object
School District       object
School Elementary     object
School Middle         object
School High           object
Sq Ft Total          float64
Price Sq Ft Sold      object
Lot Size             float64
Year Built           float64
Bedrooms               int64
Baths Total          float64
New Construction        bool
Pool Private            bool
No Of Garage Cap       int64
Style                 object
CDOM                   int64
dtype: object

In [47]:
housepy_df['Close Price'] = housepy_df['Close Price'].astype(int)
housepy_df.head()

C:\Users\easha\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

,MLS Number,Street Number,Street Name,City/Location,Zip Code,List Price,Close Price,Close Date,Area,Subdivision,...,Price Sq Ft Sold,Lot Size,Year Built,Bedrooms,Baths Total,New Construction,Pool Private,No Of Garage Cap,Style,CDOM
0,85605507,823,Loper,Houston,77017,"$44,500",44500,8/3/2015 0:00,3.0,Oak Meadows Sec 01,...,$35.83,6600.0,1950.0,3,1.0,False,False,2,Traditional,81
1,67891056,9009,Freeland,Houston,77075,"$65,000",60000,8/3/2015 0:00,3.0,Easthaven,...,$45.87,7500.0,1977.0,3,2.0,False,False,0,Traditional,19
2,97810747,17503,Waverly Grove,Houston,77084,"$90,000",78500,8/3/2015 0:00,8.0,Ashley Grove,...,$94.69,3900.0,1984.0,2,1.0,False,False,1,Traditional,70
3,94468427,6619,Briar Glade,Houston,77072,"$85,900",85000,8/3/2015 0:00,28.0,Brays Village East Sec 02,...,$46.60,4050.0,1980.0,3,2.0,False,False,2,Traditional,40
4,19671424,546,Glenvale,Houston,77060,"$105,000",94000,8/3/2015 0:00,12.0,Colonial Hills,...,$86.32,6090.0,1968.0,3,1.1,False,False,1,Traditional,98

dict_list = []
for school in school_df["school_name"].unique().tolist():
    temp_dict = {"School Name": school_df.loc[school_df["school_name"]==school]["school_name"].max(), 
                 "School Type": school_df.loc[school_df["school_name"]==school]["type"].max(), 
                "Total Student": len(school_df.loc[school_df["school_name"]==school]), 
                "Total Budget": school_df.loc[school_df["school_name"]==school]["budget"].max(),
                "Per Stu Budget": (school_df.loc[school_df["school_name"]==school]["budget"].max())/(len(school_df.loc[school_df["school_name"]==school])),
                "Math Avg Score": school_df.loc[school_df["school_name"]==school]["math_score"].mean(), 
                "Reading Avg Score": school_df.loc[school_df["school_name"]==school]["reading_score"].mean(), 
                "Math Pct Pass": ((len(school_df.loc[(school_df["school_name"]==school) & (school_df["math_score"]>69)]))/(len(school_df.loc[school_df["school_name"]==school])))*100,
                "Reading Pct Pass": ((len(school_df.loc[(school_df["school_name"]==school)&(school_df["reading_score"]>69)]))/(len(school_df.loc[school_df["school_name"]==school])))*100, 
                "Overall Pass Rate": ((((len(school_df.loc[(school_df["school_name"]==school) & (school_df["math_score"]>69)]))/(len(school_df.loc[school_df["school_name"]==school])))*100 + ((len(school_df.loc[(school_df["school_name"]==school) & (school_df["reading_score"]>69)]))/(len(school_df.loc[school_df["school_name"]==school])))*100)/2)}
    
    temp_dict_list.append(temp_dict)
SchoolSummary = pd.DataFrame(temp_dict_list)
SchoolSummary 

"Affordable Housing Percentage": ((len(housepy_df.loc[(housepy_df["Market Area"]==market)&(housepy_df["Close Price"]<242136)]))
                /(len(housepy_df.loc[housepy_df["Market Area"]==market])))*100,
                
                
 Look at which subdivisions are appreciating?  
Which subdivisions declined? Which subdivisions indicate gentrification? Most valued subdivisions in Harris county

In [49]:
#Creating the total sold column alerts us that there are areas with nothing sold or a blank in the dataset

dict_list = []
for market in housepy_df["Market Area"].unique().tolist():
    temp_dict = {"Market Area": housepy_df.loc[housepy_df["Market Area"]==market]["Market Area"].max(), 
                "Sold Price": housepy_df.loc[housepy_df["Market Area"]==market]["Close Price"].median(),
                "Total Sold": len(housepy_df.loc[housepy_df["Market Area"]==market])} 
    
    dict_list.append(temp_dict)
MarketSummary = pd.DataFrame(dict_list)
MarketSummary

                         Market Area  Sold Price  Total Sold
0                         Hobby Area    135950.0        1696
1                   Bear Creek South    180000.0        2227
2                              Alief    165000.0        2315
3                        Aldine Area    141500.0        3424
4                     Eldridge North    215000.0        1338
5                  Willowbrook South    162000.0        1255
6                  Mission Bend Area    163000.0        1025
7           1960/Cypress Creek South    156000.0        3186
8                         Brays Oaks    210000.0        2329
9                       Five Corners    151000.0        1688
10                      Huffman Area    157350.0         102
11          1960/Cypress Creek North    185000.0        1432
12                     Spring Branch    332950.0        4345
13                     North Channel    159900.0        3061
14               Southbelt/Ellington    175000.0        2668
15                     Kingwood East    280000.0         691
16                   Sharpstown Area    192500.0         706
17              Medical Center South    135194.0        2446
18                    Jersey Village    216600.0         754
19                  Copperfield Area    214000.0        4198
20              Summerwood/Lakeshore    284000.0        1623
21              Oak Forest West Area    260000.0         808
22                  Katy - Southeast    399500.0         555
23                          Pearland    249900.0         146
24               Willow Meadows Area    298000.0         614
25            Tomball South/Lakewood    201500.0         108
26                   Clear Lake Area    240000.0        2821
27                   Energy Corridor    340000.0        2252
28                     Memorial West    660000.0        1777
29           Heights/Greater Heights    480000.0        5020
..                               ...         ...         ...
73                     Cypress South    197000.0           5
74                  Atascocita South    280000.0         119
75                  Atascocita North    400000.0          13
76          River Oaks Shopping Area    697500.0         256
77          Highland Village/Midlane    834950.0         154
78                   Tanglewood Area   1492500.0         390
79                           Gulfton    201500.0          30
80          Shepherd Park Plaza Area    429500.0         317
81                  Humble Area West    128000.0          41
82                             Other    177500.0          71
83            Royden Oaks/Afton Oaks    895000.0         128
84                       Spring East    150000.0          17
85                          Pasadena    105000.0           7
86                  Sugar Land South    288500.0           1
87                    Greenway Plaza    824500.0          19
88                        Rivercrest   2850000.0          15
89             Baytown/Harris County    121500.0           2
90                  Humble Area East    189900.0          11
91                  Sugar Land North    125000.0           1
92                    Kingwood South   1427000.0           2
93                   Fall Creek Area    353676.0          87
94                      Spring/Klein    199950.0           6
95                Downtown - Houston    383250.0           6
96                     South Houston    180000.0           3
97                       Alvin North    159900.0           2
98              Spring/Klein/Tomball    426000.0           2
99                       Friendswood    235500.0           1
100  Fort Bend County North/Richmond    184000.0           1
101                          Webster    284900.0           3
102                  Sugar Land West    291884.0           1

[103 rows x 3 columns]

In [51]:
#Lets Clean the Market Area data because there appears to be a zero sold somewhere in there/ market areas with only one sold.

MarketSummary.to_csv("Desktop\Cleaning_By_Market_Area.csv", index=False, header=True)

In [57]:
#Lets drop the rows with the Market Areas with not enough data
housepy_df = housepy_df[housepy_df["Market Area"]!="Other"]
housepy_df = housepy_df[housepy_df["Market Area"]!="Charnwood/Briarbend"]
housepy_df = housepy_df[housepy_df["Market Area"]!="Humble Area West"]
housepy_df = housepy_df[housepy_df["Market Area"]!="Humble Area South"]
housepy_df = housepy_df[housepy_df["Market Area"]!="Gulfton"]
housepy_df = housepy_df[housepy_df["Market Area"]!="Greenway Plaza"]
housepy_df = housepy_df[housepy_df["Market Area"]!="Spring East"]
housepy_df = housepy_df[housepy_df["Market Area"]!="Atascocita North"]
housepy_df = housepy_df[housepy_df["Market Area"]!="Humble Area East"]
housepy_df = housepy_df[housepy_df["Market Area"]!="Pasadena"]
housepy_df = housepy_df[housepy_df["Market Area"]!="Spring/Klein"]
housepy_df = housepy_df[housepy_df["Market Area"]!="Downtown - Houston"]
housepy_df = housepy_df[housepy_df["Market Area"]!="Cypress South"]
housepy_df = housepy_df[housepy_df["Market Area"]!="South Houston"]
housepy_df = housepy_df[housepy_df["Market Area"]!="Webster"]
housepy_df = housepy_df[housepy_df["Market Area"]!="Baytown/Harris County"]
housepy_df = housepy_df[housepy_df["Market Area"]!="Kingwood South"]
housepy_df = housepy_df[housepy_df["Market Area"]!="Alvin North"]
housepy_df = housepy_df[housepy_df["Market Area"]!="Spring/Klein/Tomball"]
housepy_df = housepy_df[housepy_df["Market Area"]!="Sugar Land South"]
housepy_df = housepy_df[housepy_df["Market Area"]!="Sugar Land North"]
housepy_df = housepy_df[housepy_df["Market Area"]!="Friendswood"]
housepy_df = housepy_df[housepy_df["Market Area"]!="Fort Bend County North/Richmond"]
housepy_df = housepy_df[housepy_df["Market Area"]!="Sugar Land West"]

In [65]:
housepy_df.dropna(inplace=True)

In [67]:
new_dict_list = []
for market in housepy_df["Market Area"].unique().tolist():
    temp_dict1 = {"Market Area": housepy_df.loc[housepy_df["Market Area"]==market]["Market Area"].max(), 
                "Sold Price": housepy_df.loc[housepy_df["Market Area"]==market]["Close Price"].median(),
                "Total Sold": len(housepy_df.loc[housepy_df["Market Area"]==market]),
                 "Affordable Housing Percentage": ((len(housepy_df.loc[(housepy_df["Market Area"]==market)&(housepy_df["Close Price"]<242136)]))
                /(len(housepy_df.loc[housepy_df["Market Area"]==market])))*100,
                 } 
    
    new_dict_list.append(temp_dict1)
MarketSummary2 = pd.DataFrame(new_dict_list)
MarketSummary2

,Affordable Housing Percentage,Market Area,Sold Price,Total Sold
0,95.902141,Hobby Area,137200.0,1635
1,86.949924,Bear Creek South,175000.0,1977
2,86.801802,Alief,165000.0,2220
3,99.181401,Aldine Area,140000.0,3054
4,59.298780,Eldridge North,215000.0,1312
5,96.742671,Willowbrook South,161000.0,1228
6,96.292585,Mission Bend Area,163500.0,998
7,97.031802,1960/Cypress Creek South,152250.0,2830
8,61.613045,Brays Oaks,212000.0,2269
9,97.882197,Five Corners,148000.0,1511
10,79.411765,Huffman Area,152500.0,68
11,21.781437,Spring Branch,330000.0,4008
12,96.035962,North Channel,150000.0,2447
13,90.571314,Southbelt/Ellington,175000.0,2503
14,32.703488,Kingwood East,280000.0,688
15,82.969432,Sharpstown Area,193000.0,687
16,68.315508,Jersey Village,216500.0,748
17,69.579995,Copperfield Area,214995.0,4119
18,30.903010,Summerwood/Lakeshore,282000.0,1495
19,36.981132,Oak Forest West Area,260000.0,795
20,1.104972,Katy - Southeast,399990.0,543
21,52.755906,Pearland,225000.0,127
22,22.148760,Willow Meadows Area,298000.0,605
23,70.754717,Tomball South/Lakewood,201500.0,106
24,53.791291,Clear Lake Area,236000.0,2664
25,14.986251,Energy Corridor,338000.0,2182
26,0.396825,Memorial West,660000.0,1764
27,1.487463,Heights/Greater Heights,485000.0,4706
28,0.133156,Montrose,630000.0,751
29,0.135501,Rice/Museum District,850000.0,738
...,...,...,...,...
48,93.198992,Katy - North,169000.0,1985
49,57.795100,Cypress North,234894.0,898
50,0.943396,Rice Military/Washington Corridor,441995.0,1060
51,1.939058,Garden Oaks,450000.0,361
52,8.562691,Meyerland Area,364500.0,981
53,0.000000,Briargrove,811000.0,229
54,46.296296,East End Revitalized,255000.0,1188
55,98.412698,Missouri City Area,138500.0,126
56,11.188811,Medical Center Area,312450.0,286
57,2.247191,Cottage Grove,393000.0,623
58,0.000000,River Oaks Area,2078600.0,376
59,0.000000,Braeswood Place,671500.0,447
60,0.000000,Upper Kirby,775903.0,123
61,0.993377,Westchase Area,637500.0,302
62,0.000000,Galleria,647500.0,406
63,30.198020,Riverside,309000.0,202
64,3.994083,Briargrove Park/Walnutbend,443000.0,676
65,0.757576,Knollwood/Woodside Area,430000.0,396
66,0.000000,Memorial Close In,1930000.0,111
67,0.000000,Memorial Park,1242250.0,100
68,5.426357,Midtown - Houston,387376.5,258
69,12.500000,Atascocita South,286495.0,96
70,0.000000,River Oaks Shopping Area,700000.0,239
71,0.000000,Highland Village/Midlane,839900.0,151
72,0.260417,Tanglewood Area,1480500.0,384
73,0.000000,Briar Hollow,1275000.0,18
74,9.967846,Shepherd Park Plaza Area,430000.0,311
75,0.000000,Royden Oaks/Afton Oaks,895000.0,125
76,0.000000,Rivercrest,2850000.0,15
77,0.000000,Fall Creek Area,356045.0,69